"""Criando tabela de indicações

Revision ID: 1382c2f1b86e
Revises: 3776e40057a0
Create Date: 2025-04-09 14:54:24.486056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1382c2f1b86e'
down_revision: Union[str, None] = '3776e40057a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_indication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_indicador', sa.String(length=200), nullable=False),
    sa.Column('email_indicado', sa.String(length=100), nullable=False),
    sa.Column('telefone_indicado', sa.String(length=20), nullable=True),
    sa.Column('empresa_freelancer_indicada', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_indicado')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('base_indication')
    # ### end Alembic commands ###
