"""Fix existing table issues

Revision ID: 1503d4cae648
Revises: 
Create Date: 2025-02-22 23:06:59.913257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1503d4cae648'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_pf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('empresa_trabalha', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nascimento', sa.Date(), nullable=True),
    sa.Column('cidade', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=255), nullable=True),
    sa.Column('password_user', sa.String(length=255), nullable=False),
    sa.Column('atorizacoes', sa.JSON(), nullable=True),
    sa.Column('certificados', sa.JSON(), nullable=True),
    sa.Column('tipo_conta', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_pj',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user_pf', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=255), nullable=True),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.Column('cnae_primario', sa.String(length=10), nullable=True),
    sa.Column('cnae_secundario', sa.String(length=10), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('logradouro', sa.String(length=255), nullable=True),
    sa.Column('numero', sa.String(length=255), nullable=True),
    sa.Column('bairro', sa.String(length=255), nullable=True),
    sa.Column('cidade', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=255), nullable=True),
    sa.Column('tipo_empresa', sa.String(length=255), nullable=True),
    sa.Column('segmento_empresa', sa.String(length=255), nullable=True),
    sa.Column('atorizacoes', sa.JSON(), nullable=True),
    sa.Column('certificados', sa.JSON(), nullable=True),
    sa.Column('outras_infos', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_user_pf'], ['user_pf.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.drop_table('conversations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('conversation', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('user_pj')
    op.drop_table('user_pf')
    # ### end Alembic commands ###
