"""Fixando tabela de indicacoes 2

Revision ID: 15e46138b74c
Revises: 378c39fc700e
Create Date: 2025-04-09 14:40:47.401222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '15e46138b74c'
down_revision: Union[str, None] = '378c39fc700e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_validade', 'created_atUp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_validade', sa.Column('created_atUp', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True))
    # ### end Alembic commands ###
