"""Fixando tabela de indicacoes 2

Revision ID: 1b1945fda1ef
Revises: 50afaa35cc63
Create Date: 2025-04-09 14:36:18.045108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1b1945fda1ef'
down_revision: Union[str, None] = '50afaa35cc63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indications_busness_and_freelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_indicador', sa.String(length=200), nullable=False),
    sa.Column('email_indicado', sa.String(length=100), nullable=False),
    sa.Column('telefone_indicado', sa.String(length=20), nullable=True),
    sa.Column('empresa_freelancer_indicada', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_indicado')
    )
    op.drop_index('email_indicado', table_name='indications_base')
    op.drop_table('indications_base')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indications_base',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nome_indicador', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('email_indicado', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('telefone_indicado', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('empresa_freelancer_indicada', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('email_indicado', 'indications_base', ['email_indicado'], unique=True)
    op.drop_table('indications_busness_and_freelas')
    # ### end Alembic commands ###
