"""graficos para o charJS

Revision ID: 1b1f069504e1
Revises: 534b4bb58f13
Create Date: 2025-05-18 12:44:10.665251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b1f069504e1'
down_revision: Union[str, None] = '534b4bb58f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clicks_graphics', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('clicks_graphics', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('clicks_graphics', sa.Column('search_term', sa.String(length=255), nullable=True))
    op.add_column('clicks_graphics', sa.Column('ip', sa.String(length=45), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clicks_graphics', 'ip')
    op.drop_column('clicks_graphics', 'search_term')
    op.drop_column('clicks_graphics', 'state')
    op.drop_column('clicks_graphics', 'city')
    # ### end Alembic commands ###
