"""Subindo tabela de planos e assinaturas

Revision ID: 1cf59354354c
Revises: ccfc419d9cea
Create Date: 2025-05-24 16:50:18.335948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cf59354354c'
down_revision: Union[str, None] = 'ccfc419d9cea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('type_user', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'type_user')
    # ### end Alembic commands ###
