"""add type_user_sender and type_user_receiver to shares

Revision ID: 298f5b9b796d
Revises: d04f3c487962
Create Date: 2025-09-03 22:01:15.123715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '298f5b9b796d'
down_revision: Union[str, None] = 'd04f3c487962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
