"""Fixando tabela de indicacoes 3

Revision ID: 2e104fd5f478
Revises: 15e46138b74c
Create Date: 2025-04-09 14:42:02.623854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e104fd5f478'
down_revision: Union[str, None] = '15e46138b74c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
