"""Criando tabela de indicações

Revision ID: 3776e40057a0
Revises: 2e104fd5f478
Create Date: 2025-04-09 14:46:44.423100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3776e40057a0'
down_revision: Union[str, None] = '2e104fd5f478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
