"""Fixando tabela de indicacoes 2

Revision ID: 378c39fc700e
Revises: 1b1945fda1ef
Create Date: 2025-04-09 14:40:18.055111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '378c39fc700e'
down_revision: Union[str, None] = '1b1945fda1ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_validade', sa.Column('created_atUp', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_validade', 'created_atUp')
    # ### end Alembic commands ###
