"""Correção nos graficos

Revision ID: 3985b2c797d9
Revises: 79b2ccf10907
Create Date: 2025-05-27 04:01:13.062211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3985b2c797d9'
down_revision: Union[str, None] = '79b2ccf10907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clicks_graphics', sa.Column('typeUser', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clicks_graphics', 'typeUser')
    # ### end Alembic commands ###
