"""Adicionando tabela de indicacao

Revision ID: 39e963e56bd1
Revises: b768791e714a
Create Date: 2025-04-09 14:26:01.693720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39e963e56bd1'
down_revision: Union[str, None] = 'b768791e714a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
