"""Adicionando created_at à tabela email_validade

Revision ID: 3b91b9a76ef3
Revises: 63c201e47da9
Create Date: 2025-02-23 17:01:27.481757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b91b9a76ef3'
down_revision: Union[str, None] = '63c201e47da9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_freelancer', 'nascimento',
               existing_type=sa.DATE(),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.alter_column('user_pf', 'nascimento',
               existing_type=sa.DATE(),
               type_=sa.String(length=15),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_pf', 'nascimento',
               existing_type=sa.String(length=15),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('user_freelancer', 'nascimento',
               existing_type=sa.String(length=15),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
