"""Adicionando grafico por acesso a pagina

Revision ID: 3c5fad94c39d
Revises: a97031639449
Create Date: 2025-05-15 11:31:30.380563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c5fad94c39d'
down_revision: Union[str, None] = 'a97031639449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clicks_graphics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_busness', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts_graphics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_busness', sa.String(length=200), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts_graphics')
    op.drop_table('clicks_graphics')
    # ### end Alembic commands ###
