"""adicionando novas colunas

Revision ID: 4957b01a46f1
Revises: d2a8674d0a76
Create Date: 2025-03-05 12:14:02.668329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4957b01a46f1'
down_revision: Union[str, None] = 'd2a8674d0a76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_freelancer', sa.Column('logradouro', sa.String(length=255), nullable=True))
    op.add_column('user_freelancer', sa.Column('numero', sa.String(length=255), nullable=True))
    op.add_column('user_freelancer', sa.Column('bairro', sa.String(length=255), nullable=True))
    op.add_column('user_freelancer', sa.Column('complemento', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_freelancer', 'complemento')
    op.drop_column('user_freelancer', 'bairro')
    op.drop_column('user_freelancer', 'numero')
    op.drop_column('user_freelancer', 'logradouro')
    # ### end Alembic commands ###
