"""create avaliacoes tables

Revision ID: 4b7675ff38a7
Revises: 2d2d1a6780e1
Create Date: 2025-10-28 04:13:16.081291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b7675ff38a7'
down_revision: Union[str, None] = '2d2d1a6780e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avaliacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_avaliador', sa.String(length=200), nullable=False),
    sa.Column('numero_avaliador', sa.String(length=20), nullable=False),
    sa.Column('id_avaliado', sa.Integer(), nullable=False),
    sa.Column('tipo_avaliado', sa.String(length=50), nullable=False),
    sa.Column('nota_atendimento', sa.Float(), nullable=False),
    sa.Column('nota_preco', sa.Float(), nullable=False),
    sa.Column('nota_qualidade', sa.Float(), nullable=False),
    sa.Column('media_total', sa.Float(), nullable=False),
    sa.Column('servico_prestado', sa.String(length=500), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_avaliador', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avaliacoes_id'), 'avaliacoes', ['id'], unique=False)
    op.create_index(op.f('ix_avaliacoes_id_avaliado'), 'avaliacoes', ['id_avaliado'], unique=False)
    op.create_table('avaliacoes_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('id_avaliado', sa.Integer(), nullable=False),
    sa.Column('tipo_avaliado', sa.String(length=50), nullable=False),
    sa.Column('servico_prestado', sa.String(length=500), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.Column('avaliacao_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('usado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avaliacoes_links_id'), 'avaliacoes_links', ['id'], unique=False)
    op.create_index(op.f('ix_avaliacoes_links_token'), 'avaliacoes_links', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_avaliacoes_links_token'), table_name='avaliacoes_links')
    op.drop_index(op.f('ix_avaliacoes_links_id'), table_name='avaliacoes_links')
    op.drop_table('avaliacoes_links')
    op.drop_index(op.f('ix_avaliacoes_id_avaliado'), table_name='avaliacoes')
    op.drop_index(op.f('ix_avaliacoes_id'), table_name='avaliacoes')
    op.drop_table('avaliacoes')
    # ### end Alembic commands ###
