"""Fixando tabela de indicacoes

Revision ID: 50afaa35cc63
Revises: 519a9b7f6047
Create Date: 2025-04-09 14:32:58.275595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50afaa35cc63'
down_revision: Union[str, None] = '519a9b7f6047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indications_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_indicador', sa.String(length=200), nullable=False),
    sa.Column('email_indicado', sa.String(length=100), nullable=False),
    sa.Column('telefone_indicado', sa.String(length=20), nullable=True),
    sa.Column('empresa_freelancer_indicada', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_indicado')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indications_base')
    # ### end Alembic commands ###
