"""Fixando tabela de indicacoes

Revision ID: 519a9b7f6047
Revises: c67c0ddc96c9
Create Date: 2025-04-09 14:32:21.056429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '519a9b7f6047'
down_revision: Union[str, None] = 'c67c0ddc96c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
