"""Adicionando tabela de fotos e documentos

Revision ID: 534b4bb58f13
Revises: 28e5d2204aa1
Create Date: 2025-05-17 14:49:37.035574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '534b4bb58f13'
down_revision: Union[str, None] = '28e5d2204aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('type_user', sa.String(length=255), nullable=True),
    sa.Column('typePlan', sa.String(length=255), nullable=True),
    sa.Column('urlPhoto', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_photo_id'), 'plan_photo', ['id'], unique=False)
    op.create_table('profile_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('type_user', sa.String(length=255), nullable=True),
    sa.Column('urlPhoto', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_photo_id'), 'profile_photo', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_photo_id'), table_name='profile_photo')
    op.drop_table('profile_photo')
    op.drop_index(op.f('ix_plan_photo_id'), table_name='plan_photo')
    op.drop_table('plan_photo')
    # ### end Alembic commands ###
