"""add_performance_indexes

Revision ID: 5bad70a3733d
Revises: 2c3cdbf96372
Create Date: 2025-12-14 09:56:55.359428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5bad70a3733d'
down_revision: Union[str, None] = '2c3cdbf96372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Removing table drops that were incorrectly generated
    
    # Adding indexes for shares if they don't exist
    try:
        op.create_index('idx_shares_shared_with_type', 'shares', ['shared_with_user_id', 'type_user_receiver'], unique=False)
    except Exception:
        pass
        
    try:
        op.create_index('idx_shares_unique_check', 'shares', ['node_id', 'shared_with_user_id', 'shared_by_user_id'], unique=False)
    except Exception:
        pass

    # storage_nodes indexes
    try:
        op.create_index('idx_storage_nodes_owner_active', 'storage_nodes', ['business_id', 'type_user', 'deleted_at'], unique=False)
    except Exception:
        pass
        
    try:
        op.create_index('idx_storage_nodes_parent_deleted', 'storage_nodes', ['parent_id', 'deleted_at'], unique=False)
    except Exception:
        pass

    # Individual column indexes if missing
    for idx_name, col_name in [
        ('ix_storage_nodes_business_id', 'business_id'),
        ('ix_storage_nodes_parent_id', 'parent_id'),
        ('ix_storage_nodes_status', 'status'),
        ('ix_storage_nodes_type', 'type'),
        ('ix_storage_nodes_type_user', 'type_user')
    ]:
        try:
            op.create_index(op.f(idx_name), 'storage_nodes', [col_name], unique=False)
        except Exception:
            pass

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_storage_nodes_type_user'), table_name='storage_nodes')
    op.drop_index(op.f('ix_storage_nodes_type'), table_name='storage_nodes')
    op.drop_index(op.f('ix_storage_nodes_status'), table_name='storage_nodes')
    op.drop_index(op.f('ix_storage_nodes_parent_id'), table_name='storage_nodes')
    op.drop_index(op.f('ix_storage_nodes_business_id'), table_name='storage_nodes')
    op.drop_index('idx_storage_nodes_parent_deleted', table_name='storage_nodes')
    op.drop_index('idx_storage_nodes_owner_active', table_name='storage_nodes')
    op.alter_column('storage_nodes', 'company_type',
               existing_type=mysql.VARCHAR(length=50),
               comment='Tipo da empresa',
               existing_comment='Tipo da empresa (pf/pj/freelancer)',
               existing_nullable=True)
    op.alter_column('storage_nodes', 'company_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='ID da empresa responsável',
               existing_comment='ID da empresa responsável (para filtrar arquivos)',
               existing_nullable=True)
    op.alter_column('storage_nodes', 'type_user',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='Tipo do usuário dono (pf/pj/freelancer)',
               existing_nullable=True)
    op.alter_column('storage_nodes', 'business_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='ID do usuário dono (quem fez upload)',
               existing_nullable=True)
    op.drop_constraint(None, 'shares', type_='foreignkey')
    op.create_foreign_key('shares_ibfk_1', 'shares', 'storage_nodes', ['node_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_shares_shared_with_user_id'), table_name='shares')
    op.drop_index(op.f('ix_shares_id'), table_name='shares')
    op.drop_index('idx_shares_unique_check', table_name='shares')
    op.drop_index('idx_shares_shared_with_type', table_name='shares')
    op.create_index('ix_shares_shared_with', 'shares', ['shared_with_user_id'], unique=False)
    op.create_table('avaliacoes_Salexpress',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('avaliacao_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('nome_avaliador', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('email_avaliador', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('nota_busca_fornecedor', mysql.FLOAT(), nullable=False, comment='Como você avalia a experiência de buscar um fornecedor pela plataforma Salexpress?'),
    sa.Column('comentario_experiencia', mysql.TEXT(), nullable=True, comment='Comentário sobre a experiência na plataforma'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('ip_avaliador', mysql.VARCHAR(length=45), nullable=True),
    sa.ForeignKeyConstraint(['avaliacao_id'], ['avaliacoes.id'], name='avaliacoes_Salexpress_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_avaliacoes_Salexpress_avaliacao_id', 'avaliacoes_Salexpress', ['avaliacao_id'], unique=False)
    op.create_table('company_collaborators',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('company_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='ID da empresa à qual pertence'),
    sa.Column('company_type', mysql.VARCHAR(length=20), nullable=False, comment='Tipo da empresa (pf/pj/freelancer)'),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False, comment='Email para login'),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False, comment='Senha criptografada'),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False, comment='Nome completo'),
    sa.Column('permissions', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=False, comment='Permissões em formato JSON'),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='Colaborador ativo?'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_collaborator_email', 'company_collaborators', ['email'], unique=False)
    op.create_index('idx_collaborator_company', 'company_collaborators', ['company_id', 'company_type'], unique=False)
    op.create_index('email_2', 'company_collaborators', ['email'], unique=True)
    op.create_index('email', 'company_collaborators', ['email'], unique=True)
    op.create_table('document_logs',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('node_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='ID do documento/pasta'),
    sa.Column('action', mysql.VARCHAR(length=50), nullable=False, comment='Ação: created, moved, edited, renamed, deleted, shared, unshared'),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='ID do usuário que fez a ação'),
    sa.Column('user_type', mysql.VARCHAR(length=20), nullable=False, comment='Tipo: pf, pj, freelancer, collaborator'),
    sa.Column('user_name', mysql.VARCHAR(length=255), nullable=True, comment='Nome do usuário (cache)'),
    sa.Column('user_email', mysql.VARCHAR(length=255), nullable=True, comment='Email do usuário (cache)'),
    sa.Column('details', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True, comment='Detalhes da ação em JSON'),
    sa.Column('ip_address', mysql.VARCHAR(length=45), nullable=True, comment='IP do usuário'),
    sa.Column('user_agent', mysql.VARCHAR(length=500), nullable=True, comment='User agent do navegador'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_user_id', 'document_logs', ['user_id'], unique=False)
    op.create_index('idx_node_id', 'document_logs', ['node_id'], unique=False)
    op.create_index('idx_node_created', 'document_logs', ['node_id', 'created_at'], unique=False)
    op.create_index('idx_node_action', 'document_logs', ['node_id', 'action'], unique=False)
    op.create_index('idx_created_at', 'document_logs', ['created_at'], unique=False)
    op.create_index('idx_action', 'document_logs', ['action'], unique=False)
    # ### end Alembic commands ###
