"""Adicionando created_at à tabela email_validade

Revision ID: 63c201e47da9
Revises: 8177f7be934c
Create Date: 2025-02-23 13:41:37.718592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '63c201e47da9'
down_revision: Union[str, None] = '8177f7be934c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_freelancer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('empresa_trabalha', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nascimento', sa.Date(), nullable=True),
    sa.Column('cidade', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=255), nullable=True),
    sa.Column('atorizacoes', sa.JSON(), nullable=True),
    sa.Column('certificados', sa.JSON(), nullable=True),
    sa.Column('tipo_conta', sa.String(length=255), nullable=True),
    sa.Column('com_oque_trabalha', sa.String(length=255), nullable=True),
    sa.Column('site_portifolio', sa.String(length=255), nullable=True),
    sa.Column('linkedin', sa.String(length=255), nullable=True),
    sa.Column('marketplace', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('password_user', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.add_column('user_pf', sa.Column('status', sa.Boolean(), nullable=True))
    op.add_column('user_pj', sa.Column('id_user_freelancer', sa.Integer(), nullable=True))
    op.add_column('user_pj', sa.Column('marketplace', sa.Boolean(), nullable=True))
    op.add_column('user_pj', sa.Column('status', sa.Boolean(), nullable=True))
    op.alter_column('user_pj', 'id_user_pf',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('user_pj', 'outras_infos',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=10000),
               existing_nullable=True)
    op.create_foreign_key(None, 'user_pj', 'user_freelancer', ['id_user_freelancer'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_pj', type_='foreignkey')
    op.alter_column('user_pj', 'outras_infos',
               existing_type=sa.String(length=10000),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('user_pj', 'id_user_pf',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('user_pj', 'status')
    op.drop_column('user_pj', 'marketplace')
    op.drop_column('user_pj', 'id_user_freelancer')
    op.drop_column('user_pf', 'status')
    op.drop_table('user_freelancer')
    # ### end Alembic commands ###
