"""correções sobre o user PJ

Revision ID: 6d01ab2fb039
Revises: a28f0b0f0787
Create Date: 2025-02-23 19:51:43.316439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d01ab2fb039'
down_revision: Union[str, None] = 'a28f0b0f0787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
