"""tempo de criação

Revision ID: 6f42ba609f4c
Revises: e0f7361914bd
Create Date: 2025-04-16 13:21:49.046822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f42ba609f4c'
down_revision: Union[str, None] = 'e0f7361914bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_freelancer', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_pf', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_pj', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_pj', 'created_at')
    op.drop_column('user_pf', 'created_at')
    op.drop_column('user_freelancer', 'created_at')
    # ### end Alembic commands ###
