"""Subindo tabela de planos e assinaturas

Revision ID: 79b2ccf10907
Revises: 1cf59354354c
Create Date: 2025-05-24 16:55:37.973348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79b2ccf10907'
down_revision: Union[str, None] = '1cf59354354c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
