"""adicionar_tabelas_notificacoes_documentos

Revision ID: 7b345a31b38c
Revises: d1922e0df036
Create Date: 2025-11-08 11:54:20.256780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b345a31b38c'
down_revision: Union[str, None] = 'd1922e0df036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_followers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tipo_usuario', sa.String(length=20), nullable=False),
    sa.Column('dias_antes_alerta', sa.Integer(), nullable=False),
    sa.Column('alertar_no_vencimento', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['storage_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_followers_id'), 'document_followers', ['id'], unique=False)
    op.create_index(op.f('ix_document_followers_node_id'), 'document_followers', ['node_id'], unique=False)
    op.create_index(op.f('ix_document_followers_user_id'), 'document_followers', ['user_id'], unique=False)
    op.create_table('document_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tipo_usuario', sa.String(length=20), nullable=False),
    sa.Column('email_destinatario', sa.String(length=255), nullable=False),
    sa.Column('tipo_notificacao', sa.String(length=50), nullable=False),
    sa.Column('dias_para_vencimento', sa.Integer(), nullable=True),
    sa.Column('documento_nome', sa.String(length=255), nullable=False),
    sa.Column('documento_data_validade', sa.DateTime(), nullable=False),
    sa.Column('enviada', sa.Boolean(), nullable=False),
    sa.Column('erro_envio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('enviada_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['storage_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_notifications_id'), 'document_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_document_notifications_node_id'), 'document_notifications', ['node_id'], unique=False)
    op.create_index(op.f('ix_document_notifications_user_id'), 'document_notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_notifications_user_id'), table_name='document_notifications')
    op.drop_index(op.f('ix_document_notifications_node_id'), table_name='document_notifications')
    op.drop_index(op.f('ix_document_notifications_id'), table_name='document_notifications')
    op.drop_table('document_notifications')
    op.drop_index(op.f('ix_document_followers_user_id'), table_name='document_followers')
    op.drop_index(op.f('ix_document_followers_node_id'), table_name='document_followers')
    op.drop_index(op.f('ix_document_followers_id'), table_name='document_followers')
    op.drop_table('document_followers')
    # ### end Alembic commands ###
    op.drop_table('document_followers')
    # ### end Alembic commands ###
