"""Adicionando grafico por acesso a pagina

Revision ID: 7f4a9cfc4379
Revises: dc8c4dd2e35c
Create Date: 2025-05-15 11:16:21.948942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f4a9cfc4379'
down_revision: Union[str, None] = 'dc8c4dd2e35c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
