"""Adicionando created_at à tabela email_validade

Revision ID: 8177f7be934c
Revises: 1503d4cae648
Create Date: 2025-02-23 01:10:44.177910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8177f7be934c'
down_revision: Union[str, None] = '1503d4cae648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_validade', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_validade', 'created_at')
    # ### end Alembic commands ###
