"""Opções de solicitação contato e salvar dados do site da empresa

Revision ID: 89bc61984ee7
Revises: 3985b2c797d9
Create Date: 2025-06-03 01:17:29.436517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89bc61984ee7'
down_revision: Union[str, None] = '3985b2c797d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_user', sa.String(length=255), nullable=False),
    sa.Column('id_busness', sa.Integer(), nullable=False),
    sa.Column('dados_site', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_data_id'), 'business_data', ['id'], unique=False)
    op.create_table('contacts_solicitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=255), nullable=False),
    sa.Column('termos_aceitos', sa.Boolean(), nullable=True),
    sa.Column('id_busness', sa.Integer(), nullable=False),
    sa.Column('type_user', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts_solicitations')
    op.drop_index(op.f('ix_business_data_id'), table_name='business_data')
    op.drop_table('business_data')
    # ### end Alembic commands ###
