"""correções sobre o user PJ

Revision ID: 92bb6ee4fa57
Revises: e5b5851b4588
Create Date: 2025-02-23 19:45:55.176264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '92bb6ee4fa57'
down_revision: Union[str, None] = 'e5b5851b4588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_pj_ibfk_2', 'user_pj', type_='foreignkey')
    op.drop_column('user_pj', 'id_user_freelancer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_pj', sa.Column('id_user_freelancer', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('user_pj_ibfk_2', 'user_pj', 'user_freelancer', ['id_user_freelancer'], ['id'])
    # ### end Alembic commands ###
