"""correções sobre o user PJ

Revision ID: a28f0b0f0787
Revises: 92bb6ee4fa57
Create Date: 2025-02-23 19:50:15.704596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a28f0b0f0787'
down_revision: Union[str, None] = '92bb6ee4fa57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_pf', 'certificados')
    op.drop_column('user_pf', 'atorizacoes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_pf', sa.Column('atorizacoes', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
    op.add_column('user_pf', sa.Column('certificados', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
    # ### end Alembic commands ###
