"""add status to avaliacoes

Revision ID: a77049d09c87
Revises: 4b7675ff38a7
Create Date: 2025-10-28 10:35:43.569684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a77049d09c87'
down_revision: Union[str, None] = '4b7675ff38a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avaliacoes', sa.Column('status', sa.String(length=50), nullable=False, server_default='AGUARDANDO_APROVACAO'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('avaliacoes', 'status')
    # ### end Alembic commands ###
