"""Adicionando grafico por acesso a pagina

Revision ID: a97031639449
Revises: 7f4a9cfc4379
Create Date: 2025-05-15 11:29:50.450288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a97031639449'
down_revision: Union[str, None] = '7f4a9cfc4379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
