"""Criando tabela de indicacao

Revision ID: b1dee2901565
Revises: 1382c2f1b86e
Create Date: 2025-04-09 14:55:18.482437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b1dee2901565'
down_revision: Union[str, None] = '1382c2f1b86e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indication_bn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_indicador', sa.String(length=200), nullable=False),
    sa.Column('email_indicado', sa.String(length=100), nullable=False),
    sa.Column('telefone_indicado', sa.String(length=20), nullable=True),
    sa.Column('empresa_freelancer_indicada', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_indicado')
    )
    op.drop_index('email_indicado', table_name='indications_busness_and_freelas')
    op.drop_table('indications_busness_and_freelas')
    op.drop_index('email_indicado', table_name='base_indication')
    op.drop_table('base_indication')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_indication',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nome_indicador', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('email_indicado', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('telefone_indicado', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('empresa_freelancer_indicada', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('email_indicado', 'base_indication', ['email_indicado'], unique=True)
    op.create_table('indications_busness_and_freelas',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nome_indicador', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('email_indicado', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('telefone_indicado', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('empresa_freelancer_indicada', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('email_indicado', 'indications_busness_and_freelas', ['email_indicado'], unique=True)
    op.drop_table('indication_bn')
    # ### end Alembic commands ###
