"""Adicionando tabela de indicacao

Revision ID: b768791e714a
Revises: 7bf7dd737c59
Create Date: 2025-04-09 14:14:37.754257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b768791e714a'
down_revision: Union[str, None] = '7bf7dd737c59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
