"""Fixando tabela de indicacoes

Revision ID: c67c0ddc96c9
Revises: 39e963e56bd1
Create Date: 2025-04-09 14:26:51.465669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c67c0ddc96c9'
down_revision: Union[str, None] = '39e963e56bd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
