"""Subindo tabela de planos e assinaturas

Revision ID: ccfc419d9cea
Revises: 159dfe08c82b
Create Date: 2025-05-24 16:32:17.791024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccfc419d9cea'
down_revision: Union[str, None] = '159dfe08c82b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('subscriptions', sa.Column('tipo_pagamento', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'tipo_pagamento')
    op.drop_column('subscriptions', 'price')
    # ### end Alembic commands ###
