"""add type_user_sender and type_user_receiver to shares

Revision ID: d04f3c487962
Revises: a1b2c3d4e5f6
Create Date: 2025-09-03 16:54:03.153803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd04f3c487962'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Cria tabela shares (caso ainda não exista em ambientes que perderam migration anterior)
    if not op.get_bind().dialect.has_table(op.get_bind(), 'shares'):  # type: ignore
        op.create_table(
            'shares',
            sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
            sa.Column('node_id', sa.Integer(), sa.ForeignKey('storage_nodes.id'), nullable=False),
            sa.Column('shared_with_user_id', sa.Integer(), nullable=False),
            sa.Column('shared_by_user_id', sa.Integer(), nullable=False),
            sa.Column('type_user_sender', sa.String(length=50), nullable=True),
            sa.Column('type_user_receiver', sa.String(length=50), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP')),
        )
    else:
        # Adiciona colunas novas se a tabela já existir
        inspector = sa.inspect(op.get_bind())
        cols = [c['name'] for c in inspector.get_columns('shares')]
        if 'type_user_sender' not in cols:
            op.add_column('shares', sa.Column('type_user_sender', sa.String(length=50), nullable=True))
        if 'type_user_receiver' not in cols:
            op.add_column('shares', sa.Column('type_user_receiver', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove colunas adicionadas (não dropa a tabela para não perder dados)
    inspector = sa.inspect(op.get_bind())
    cols = [c['name'] for c in inspector.get_columns('shares')]
    if 'type_user_sender' in cols:
        op.drop_column('shares', 'type_user_sender')
    if 'type_user_receiver' in cols:
        op.drop_column('shares', 'type_user_receiver')
    # ### end Alembic commands ###
