"""add data_validade to storage_nodes

Revision ID: d1922e0df036
Revises: 9b658785976e
Create Date: 2025-11-08 11:03:42.591544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1922e0df036'
down_revision: Union[str, None] = '9b658785976e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storage_nodes', sa.Column('data_validade', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storage_nodes', 'data_validade')
    # ### end Alembic commands ###
