"""Corrige nome da coluna descricaoServico

Revision ID: d200915d49aa
Revises: f8f52ad05943
Create Date: 2025-03-05 11:22:07.424393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd200915d49aa'
down_revision: Union[str, None] = 'f8f52ad05943'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_freelancer', sa.Column('termos_aceitos', sa.Boolean(), nullable=True))
    op.add_column('user_freelancer', sa.Column('politicas_aceitas', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_freelancer', 'politicas_aceitas')
    op.drop_column('user_freelancer', 'termos_aceitos')
    # ### end Alembic commands ###
