"""Opções de solicitação contato e salvar dados do site da empresa

Revision ID: d21c3253e38d
Revises: 89bc61984ee7
Create Date: 2025-06-03 02:14:04.911927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd21c3253e38d'
down_revision: Union[str, None] = '89bc61984ee7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='contacts_solicitations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('email', 'contacts_solicitations', ['email'], unique=True)
    # ### end Alembic commands ###
