"""adicionando novas colunas

Revision ID: d2a8674d0a76
Revises: d200915d49aa
Create Date: 2025-03-05 12:11:13.600822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2a8674d0a76'
down_revision: Union[str, None] = 'd200915d49aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_pj', sa.Column('complemento', sa.String(length=255), nullable=True))
    op.add_column('user_pj', sa.Column('descricaoServico', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_pj', 'descricaoServico')
    op.drop_column('user_pj', 'complemento')
    # ### end Alembic commands ###
