"""Aumentando caracteres na descrição do serviço

Revision ID: dc8c4dd2e35c
Revises: 6f42ba609f4c
Create Date: 2025-05-06 13:17:13.006188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dc8c4dd2e35c'
down_revision: Union[str, None] = '6f42ba609f4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_freelancer', 'descricaoServico',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('user_pj', 'descricaoServico',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_pj', 'descricaoServico',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('user_freelancer', 'descricaoServico',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
