"""tabela de permissoes

Revision ID: e0f7361914bd
Revises: 04751c495235
Create Date: 2025-04-15 23:43:31.437743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0f7361914bd'
down_revision: Union[str, None] = '04751c495235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions_users_freelancers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user_freelancer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_users_freelancers_id'), 'permissions_users_freelancers', ['id'], unique=False)
    op.create_table('permissions_users_pj',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user_pf.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_users_pj_id'), 'permissions_users_pj', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permissions_users_pj_id'), table_name='permissions_users_pj')
    op.drop_table('permissions_users_pj')
    op.drop_index(op.f('ix_permissions_users_freelancers_id'), table_name='permissions_users_freelancers')
    op.drop_table('permissions_users_freelancers')
    # ### end Alembic commands ###
