"""Adicionand data nas indicações

Revision ID: f6142db296ad
Revises: f16878e5b0da
Create Date: 2025-04-15 22:36:42.135275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6142db296ad'
down_revision: Union[str, None] = 'f16878e5b0da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indication_busness', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indication_busness', 'created_at')
    # ### end Alembic commands ###
