"""Adicionando created_at à tabela email_validade

Revision ID: f757283b3970
Revises: 6d01ab2fb039
Create Date: 2025-02-23 19:52:38.567557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f757283b3970'
down_revision: Union[str, None] = '6d01ab2fb039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
