"""Corrige nome da coluna descricaoServico

Revision ID: f8f52ad05943
Revises: 266604d4faa2
Create Date: 2025-03-05 11:16:10.183527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8f52ad05943'
down_revision: Union[str, None] = '266604d4faa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_freelancer', sa.Column('descricaoServico', sa.String(length=255), nullable=True))
    op.add_column('user_pj', sa.Column('termos_aceitos', sa.Boolean(), nullable=True))
    op.add_column('user_pj', sa.Column('politicas_aceitas', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_pj', 'politicas_aceitas')
    op.drop_column('user_pj', 'termos_aceitos')
    op.drop_column('user_freelancer', 'descricaoServico')
    # ### end Alembic commands ###
